### ISSUE TITLE
ics_calendar 4.0.0 and later gives strange error after update

### ISSUE THREAD

**Issue by acato** [franc6/ics_calendar#102]
Since upgrading to 2023.10.3 and Supervisor 2023.10.0 the integration fails to load with errors

Unable to prepare setup for platform ics_calendar.calendar: Unable to set up component.
7:42:48 AM – (ERROR) setup.py
Error during setup of component ics_calendar
7:42:48 AM – (ERROR) setup.py

2023-10-18 07:42:48.386 ERROR (MainThread) [homeassistant.setup] Error during setup of component ics_calendar
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
result = await task
^^^^^^^^^^
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ics_calendar/__init__.py", line 98, in setup
PLATFORMS[0], DOMAIN, config[DOMAIN], config
~~~~~~^^^^^^^^
KeyError: 'ics_calendar'
2023-10-18 07:42:48.391 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform ics_calendar.calendar: Unable to set up component.

**Comment by franc6** [comment]
The error suggests that you updated to 4.0.0, but didn't update the yaml configuration correctly.  I'm running 2023.10.3 and ics_calendar 4.0.0, and I don't see the errors.  If you can post your config, I can help correct it.  Just be sure not to include your actual URL, or any username or password.  Just put dummy strings in for them, as it's the configuration format that would be the problem. :)

Thanks!

**Comment by acato** [comment]
Thanks. This is the relevant config section:

calendar:
- platform: ics_calendar
  calendars:
      - name: "calendar 1"
        url: "http://ical-cdn.*****"
      - name: "Calendar 2"
        url: "http://ical-cdn.****"
      - name: "Calendar 3"
        url: "webcal://ics.***"
      - name: "Calendar 4"
        url: "https://www.***"

**Comment by franc6** [comment]
Hmm... Maybe I didn't test having no config at all...  Anyway, it seems that you updated ics_calendar to v4, but didn't update the config at all.  Please see [UpgradeTo4.0AndLater.md](https://github.com/franc6/ics_calendar/blob/releases/UpgradeTo4.0AndLater.md) for info on updating the configuration.  

And, it seems I have a bug to fix, too.  It shouldn't have given an error with your config, although, I'm thinking giving some clear error message would be desirable.

Q: Do you know how you updated ics_calendar?  If I can do something to be sure people see a note about the configuration change, I'd like to do so. 

Thanks for the report!

**Comment by acato** [comment]
That was it. I had completely missed that I was supposed to change the config. An error message that points to the page with the instructions on how to fix it would be perfect. Thanks for jumping on this right away. Closing as fixed.

**Comment by franc6** [comment]
Thanks for the info.  I'm keeping this open until I have a chance to give a useful error message.

Besides, if you missed it, somebody else will miss it, too, and if they see an issue that looks similar, that could help them.

**Comment by franc6** [comment]
v4.0.1 adds an error message with explanation, however, in my instance of HA, I couldn't reproduce the problem at all.  I'm keeping this open for a while, in case someone else runs into this problem.

**Comment by franc6** [comment]
Closing for lack of feedback on the error message...  Note to self: Re-open if you see someone report a similar error!
