### ISSUE TITLE
setup_platform

### ISSUE THREAD

**Issue by aladin2000** [franc6/ics_calendar#136]
I got that error in last  HASSIO release 2024.5.3
 

the Homeassistant.log 

```
2024-05-13 18:34:36.764 ERROR (MainThread) [homeassistant.components.calendar] Error while setting up ics_calendar platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/calendar.py", line 79, in setup_platform
    for calendar in calendars:
TypeError: 'NoneType' object is not iterable
```

**Comment by franc6** [comment]
While the actual error is different, I think this is the same as #102.  Can you please verify your configuration, and reply with the configuration if you believe it is correct?

Thanks!
