### ISSUE TITLE
Error during setup of component ics_calendar

### ISSUE THREAD

**Issue by ddiascro** [franc6/ics_calendar#185]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version: 2024.10.4

Installation Type (put an X between the square brackets for your HA):
[x] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[x] x86-64

**Describe the bug**
Upgrading from 5.0.2 to 5.0.4 I get the following error in the logs.  I had the same issue upgrading to 5.0.3.  A rollback to 5.0.2 restores functionality.

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 11:23:59 AM (1 occurrences)
Last logged: 11:23:59 AM

Error during setup of component ics_calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/ics_calendar/__init__.py", line 159, in async_setup
    hass.async_create_task(
  File "/usr/src/homeassistant/homeassistant/core.py", line 807, in async_create_task
    return self.async_create_task_internal(target, name, eager_start)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 829, in async_create_task_internal
    task = create_eager_task(target, name=name, loop=self.loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a coroutine was expected, got True

**Comment by franc6** [comment]
This will be fixed with the 5.0.6 release.
