### ISSUE TITLE
Failed to parse ICS

### ISSUE THREAD

**Issue by GorCed** [franc6/ics_calendar#191]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version: 5.0.4

Installation Type (put an X between the square brackets for your HA):
[] Home Assistant OS
[X] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[X] x86-64

**Describe the bug**
Some of my configured calenders started failing some time ago (about 2 weeks) 
The calendars are empty and no new entrys gets added.

after some digging I found the "Failed to parse ICS" error in the log.

any ideas of what could be wrong?

{
2024-11-19 12:07:11.329 DEBUG (MainThread) [custom_components.ics_calendar.calendar] Initializing calendar: SIS_240918 with URL: https://cal.laget.se/SIS_Klubbsida-Ishockey-D2Hockey-16.ics
2024-11-19 12:07:11.333 DEBUG (SyncWorker_23) [custom_components.ics_calendar.calendar] SIS_240918: Update was called
2024-11-19 12:07:11.333 DEBUG (SyncWorker_23) [custom_components.ics_calendar.calendar] SIS_240918: download_calendar start
2024-11-19 12:07:11.333 DEBUG (SyncWorker_23) [custom_components.ics_calendar.calendar] SIS_240918: download_calendar lock acquired
2024-11-19 12:07:11.333 DEBUG (SyncWorker_23) [custom_components.ics_calendar.calendar] SIS_240918: Downloading calendar data from: https://cal.laget.se/SIS_Klubbsida-Ishockey-D2Hockey-16.ics
2024-11-19 12:07:11.333 DEBUG (SyncWorker_23) [custom_components.ics_calendar.calendar] SIS_240918: _download_data start
2024-11-19 12:07:11.405 DEBUG (SyncWorker_23) [custom_components.ics_calendar.calendar] SIS_240918: _download_data done
2024-11-19 12:07:11.405 DEBUG (SyncWorker_23) [custom_components.ics_calendar.calendar] SIS_240918: download_calendar done
2024-11-19 12:07:11.405 DEBUG (SyncWorker_23) [custom_components.ics_calendar.calendar] SIS_240918: Setting calendar content
2024-11-19 12:07:11.458 ERROR (SyncWorker_23) [custom_components.ics_calendar.calendar] update: SIS_240918: Failed to parse ICS!
Traceback (most recent call last):
  File "/config/custom_components/ics_calendar/calendar.py", line 331, in update
    self.event = self.parser.get_current_event(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 118, in get_current_event
    for event in rie.of(self._calendar).between(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 1446, in of
    return calendar_query(
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 1290, in __init__
    component_adapter.collect_series_from(calendar, self._skip_errors)
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 1191, in collect_series_from
    result.append(self._series(components))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 610, in __init__
    self.compute_span_extension()
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 615, in compute_span_extension
    self.recurrence.extend_query_span_by
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 413, in extend_query_span_by
    return self.core.extend_query_span_by
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 259, in cached_property
    self.__dict__[name] = value = func(self)
                                  ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 884, in extend_query_span_by
    subtract_from_start = self.duration
                          ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 259, in cached_property
    self.__dict__[name] = value = func(self)
                                  ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/recurring_ical_events.py", line 865, in duration
    return self.end - self.start
           ~~~~~~~~~^~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'datetime.date'
2024-11-19 12:07:11.459 DEBUG (SyncWorker_23) [custom_components.ics_calendar.calendar] SIS_240918: No event found!

}

**Comment by GorCed** [comment]
I've validated the ICS via https://icalendar.org/validator.html and it validates OK.
the file is provided by external party and I cant edit it.

any ideas?

**Comment by franc6** [comment]
You can try changing the parser to ics. That looks like a bug in the default parser.

**Comment by franc6** [comment]
@GorCed I've confirmed the problem in the default parser.  If you are OK with me sharing the ICS file, I'll open an issue with the authors of the parser itself to see if they can resolve it in a future release.  For now, the ics parser appears to be working.  Please reply soon if you're OK with me sharing the contents of that file.  I'll probably try to make the file smaller, so it's easier for the other people to find and fix.

**Comment by GorCed** [comment]
Hi.
Thanks for looking i to it.
I switched to the other parser an it works for now.

Feel free to share the ICS-file.
There are no secrets in it.

**Comment by franc6** [comment]
I was able to determine the cause of the problem, and it looks like someone else already reported it: https://github.com/niccokunzmann/python-recurring-ical-events/issues/201

I'm going ahead and closing this for now, since it's not a bug in ics_calendar.

**Comment by niccokunzmann** [comment]
This is should be fixed in v3.5.2 of recurring_ical_events.

**Comment by franc6** [comment]
Thank you, @niccokunzmann!

This has been put into the latest release (5.1.3), too.
