### ISSUE TITLE
ICS_Calendar unable to setup calendar anymore

### ISSUE THREAD

**Issue by tardich** [franc6/ics_calendar#194]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version:2024.12.0, installed in Kubernetes from Helm chart

Installation Type (put an X between the square brackets for your HA):
[] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[x] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[x] x86-64

**Describe the bug**
After updating My home-assistant installation, I realized that ics_calendar was no longer working. I uninstalled ics_calendar, restarted home_assistant,then try to reinstall it (ics_calendar). When adding my calendar through the UI mecanism, I get an error at the screen for ics_calendar that says "Failed to set up"

The home-assistant logs are telling me:

```
2024-12-05 23:30:09.791 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Commun for ics_calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/__init__.py", line 202, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, ["calendar"])
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1123, in async_get_platforms
    if platform := self._get_platform_cached_or_raise(platform_name):
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1214, in _get_platform_cached_or_raise
    raise ModuleNotFoundError(
    ...<2 lines>...
    )
ModuleNotFoundError: Platform ics_calendar.calendar not found
```

Used to work for quite a long time without hickups...

**Comment by wrichter** [comment]
Same problem, with HA 2024.12.1 and ics_calendar HEAD version, HA startup with an existing ICS calendar config:

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/__init__.py", line 202, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, ["calendar"])
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1154, in async_get_platforms
    await self.hass.async_add_import_executor_job(
        self._load_platforms, platform_names
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1097, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ics_calendar/calendar.py", line 48, in <module>
    from .getparser import GetParser
  File "/config/custom_components/ics_calendar/getparser.py", line 4, in <module>
    from .parsers.parser_ics import ParserICS
  File "/config/custom_components/ics_calendar/parsers/parser_ics.py", line 9, in <module>
    from ics import Calendar
ModuleNotFoundError: No module named 'ics' 
```

**Comment by wrichter** [comment]
EDIT: red herring -- while the version did change, the root cause was in missing prereqs in the container image - see next posting

A difference I can see between the older HA container image (where ics_calendar was working) and the 2024.12.x versions is the icalendar package version has changed:

Old / works:
```
b8e3011e4cec:/config# pip list|grep -i calendar
icalendar                        6.0.1
```

New / does not work:
```
46374c0881fc:/config# pip list|grep -i calendar
icalendar                        6.1.0
```

**Comment by wrichter** [comment]
I was able to get the ics_calendar plugin to work with a containerized HA 2024.12 setup by adding the necessary package prereqs to the container image:

```
# cat Containerfile
FROM  ghcr.io/home-assistant/home-assistant:stable
RUN pip install icalendar==6.0.1 ics>=0.7.2
# podman build .
[... output omitted...]
# podman tag .... ghcr.io/home-assistant/home-assistant:stable
[... output omitted...]
```

**Comment by tardich** [comment]
I'm a little confused. Are you saying that this is the home-assistant container image (I'm using ghcr.io/home-assistant/home-assistant:2024.12.1) that is missing the above packages (so icalendar 6.0.1 and ics 0.7.2) ?

If so, this is the home-assistant container build team we need to get to update, right?

**Comment by wrichter** [comment]
Sort of… what I‘m saying is:

- we’re using the same container image (stable and 2024.12.1 currently point to the same)
- I believe I saw a similar issue in my containerized deployment (ModuleNotFoundError, although it seems to reference different modules), triggered through different code paths (UI config in your case, startup in my case)
- **My** issue went away when layering the required prerequisite modules onto the official HA container image

Assuming what you’re seeing is the same issue, we could certainly ask the HA team to (re)include the package. At the same time it is good practice from a security point of view on their end to not include packages in the container image that they do not need.

**Comment by franc6** [comment]
This is a problem with this integration. It’s just not keeping up with changes in HA core. HA doesn’t include python packages it doesn’t use, AFAICT. 

I’m aware of this problem, but my time to work on this project is limited. If you want a faster fix, create a PR that changes the icalendar requirement to require “~= 6.1” (manifest.json and pyproject.toml) and update the pyproject.toml file to require the latest version of pytest-homeassistant-custom-component.  I can let github run the tests and if it all passes make a new release.

**Comment by wrichter** [comment]
Thanks for acknowledging the problem and pointing to the right approach @franc6. To make sure I understand correctly - changing the manifest.json and pyproject.toml in the ics_calendar project will make the right dependencies appear in the running home assistant container instance?

**Comment by franc6** [comment]
It should. Those particular changes will make the dependency match what you have reported HA already has, which should remove the not found problems.

**Comment by wrichter** [comment]
I temporarily worked around the issue by adding the following startup command to the k8s deployment which installs the required python package ics on pod startup:

```
spec:
  template:
    spec:
      containers:
      - args: ["-c", "pip install ics && exec /init"]
        command: ["/bin/sh"]
        image: ghcr.io/home-assistant/home-assistant:stable
 ```

**Comment by tardich** [comment]
@wrichter Good one. I've set it this way for now. It fixed the issue for me so at least, my calendar's back. Tks for the idea.

**Comment by wrichter** [comment]
Just tested the 5.0.5 version, the problem has shifted with the changed dependencies but is not yet gone (ModuleNotFoundError: No module named 'httpx_auth'):

```
2024-12-13 08:00:37.318 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OHG Schulkalender for ics_calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/__init__.py", line 202, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, ["calendar"])
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1154, in async_get_platforms
    await self.hass.async_add_import_executor_job(
        self._load_platforms, platform_names
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1097, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ics_calendar/calendar.py", line 35, in <module>
    from .calendardata import CalendarData
  File "/config/custom_components/ics_calendar/calendardata.py", line 11, in <module>
    import httpx_auth
ModuleNotFoundError: No module named 'httpx_auth'
```

**Comment by wrichter** [comment]
The workaround is now:

```
spec:
  template:
    spec:
      containers:
      - args: ["-c", "pip install httpx_auth ics && exec /init"]
        command: ["/bin/sh"]
        image: ghcr.io/home-assistant/home-assistant:stable
```

i.e. both the package httpx_auth and ics are not available in the HA container image

**Comment by tardich** [comment]
Confirmed. I had seen the same issue. But adding httpx_auth as suggested above brought some instability. So rolled back to 5.0.4, only adding ics at runtime for now

**Comment by franc6** [comment]
See also #213 & #190.

**Comment by franc6** [comment]
After much pain and consideration, I've determined that I can't really work around this problem.  Please see the new notes in README.md.  I know that's not what anyone posting to this issue wants to read, but I'm stuck.  There's nothing I can do to make it work.  If you can reproduce the problem on a clean installation without any attempt to resolve this problem, please re-open https://github.com/home-assistant/core/issues/127966 with HA, or, if more appropriate, open a new issue with HA and note that the one I referenced is not fixed.
If you cannot reproduce the problem on a clean installation, then you probably need to clean up whatever changes you've made to fix or work-around this problem, uninstall this integration, and re-install it.
I'm really sorry, this isn't the way I wanted to close this issue, either.  :(
