### ISSUE TITLE
UnboundLocalError: local variable 'calendar_data' referenced before assignment

### ISSUE THREAD

**Issue by youseeus** [franc6/ics_calendar#20]
Hey i got this error when i upgraded to beta of today

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
    await self.hass.async_add_executor_job(self.update)  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ics/calendar.py", line 102, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/ics/calendar.py", line 180, in update
    calendar_data = self._downloadAndParseCalendar()
  File "/config/custom_components/ics/calendar.py", line 148, in _downloadAndParseCalendar
    return calendar_data
UnboundLocalError: local variable 'calendar_data' referenced before assignment
```

**Comment by franc6** [comment]
@youseeus If 2.0.0-beta7 fixes the problem for you too, please close this issue.
