### ISSUE TITLE
Post update to 5.1.0  Error message Detected blocking call to import_module with args ('tzdata.zoneinfo',)

### ISSUE THREAD

**Issue by mcpfr** [franc6/ics_calendar#212]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version core-2024.12.4

Type d'installation | Home Assistant OS

Installation Type (put an X between the square brackets for your HA):
[X] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[X] ARM
[] x86-64

**Describe the bug**

After updating 5.0.4 to 5.1.0, I have two errors when starting H.A
But this does not seem to have any impact on the operation

If you need information do not hesitate to ask me

Can you help me please

#########################################################################################
Enregistreur: homeassistant.util.loop
Source: util/loop.py:136
S'est produit pour la première fois: 16:26:52 (2 occurrences)
Dernier enregistrement: 16:26:52

Detected blocking call to import_module with args ('tzdata.zoneinfo',) inside the event loop by custom integration 'ics_calendar' at custom_components/ics_calendar/parsers/parser_rie.py, line 33: self._calendar = Calendar.from_ical(content) (offender: /usr/local/lib/python3.13/importlib/resources/_common.py, line 82: return importlib.import_module(cand)), please create a bug report at https://github.com/franc6/ics_calendar/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update await self.async_update() File "/config/custom_components/ics_calendar/calendar.py", line 220, in async_update await self.data.async_update() File "/config/custom_components/ics_calendar/calendar.py", line 343, in async_update self.parser.set_content(self._calendar_data.get()) File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 33, in set_content self._calendar = Calendar.from_ical(content)

Detected blocking call to open with args (PosixPath('/usr/local/lib/python3.13/site-packages/tzdata/zoneinfo/Romance Standard Time'), 'rb') inside the event loop by custom integration 'ics_calendar' at custom_components/ics_calendar/parsers/parser_rie.py, line 33: self._calendar = Calendar.from_ical(content) (offender: /usr/local/lib/python3.13/zoneinfo/_common.py, line 12: return resources.files(package_name).joinpath(resource_name).open("rb")), please create a bug report at https://github.com/franc6/ics_calendar/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update await self.async_update() File "/config/custom_components/ics_calendar/calendar.py", line 220, in async_update await self.data.async_update() File "/config/custom_components/ics_calendar/calendar.py", line 343, in async_update self.parser.set_content(self._calendar_data.get()) File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 33, in set_content self._calendar = Calendar.from_ical(content)

**Comment by franc6** [comment]
Note to self: The problem is the parser opening time zone info during parse. Might need to switch back to update instead of async_update? Maybe different method in parser could be used?  Not sure why my own logs don’t see this, but maybe due to ics file containing all relevant TZ data?
@gieljnssns also reported this by commenting on issue #183 -- copied relevant notes from there to here.

**Comment by mcpfr** [comment]
In addition, I use 2 ics files (2 H.A entities for one and 1 for the other)

I have for the TZ section, in the first:

```
BEGIN:VTIMEZONE
TZID:Romance Standard Time
BEGIN:STANDARD
DTSTART:16011028T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010325T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
```

in the second:


```
BEGIN:VTIMEZONE
TZID:Europe/Paris
X-LIC-LOCATION:Europe/Paris

BEGIN:DAYLIGHT
DTSTART:19700329T020000
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYMONTH=3;BYDAY=-1SU
TZNAME:CET
END:DAYLIGHT

BEGIN:STANDARD
DTSTART:19701025T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYMONTH=10;BYDAY=-1SU
END:STANDARD

END:VTIMEZONE
```

**Comment by instantdreams** [comment]
I am encountering the same issue:

`2025-04-01 08:53:20.469 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('tzdata.zoneinfo',) inside the event loop by custom integration 'ics_calendar' at custom_components/ics_calendar/parsers/parser_rie.py, line 33: self._calendar = Calendar.from_ical(content) (offender: /usr/local/lib/python3.13/importlib/resources/_common.py, line 82: return importlib.import_module(cand)), please create a bug report at https://github.com/franc6/ics_calendar/issues`

I am importing several ICS files, which include entries such as:

```
BEGIN:VTIMEZONE
TZID:Mountain Standard Time
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0600
TZOFFSETTO:-0700
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0700
TZOFFSETTO:-0600
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
```

and

```
BEGIN:VTIMEZONE
TZID:America/Edmonton
X-LIC-LOCATION:America/Edmonton
BEGIN:DAYLIGHT
TZOFFSETFROM:-0700
TZOFFSETTO:-0600
TZNAME:MDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0600
TZOFFSETTO:-0700
TZNAME:MST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
```

Another has two entries:

```
BEGIN:VTIMEZONE
TZID:America/Denver
X-LIC-LOCATION:America/Denver
BEGIN:DAYLIGHT
TZOFFSETFROM:-0700
TZOFFSETTO:-0600
TZNAME:MDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0600
TZOFFSETTO:-0700
TZNAME:MST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:America/Edmonton
X-LIC-LOCATION:America/Edmonton
BEGIN:DAYLIGHT
TZOFFSETFROM:-0700
TZOFFSETTO:-0600
TZNAME:MDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0600
TZOFFSETTO:-0700
TZNAME:MST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
```

Hope this is useful.

**Comment by bartoszperko** [comment]
Hello,

I am experiencing system freezes and loss of remote access caused by blocking calls from `ics_calendar`. The issue originates from `parser_rie.py` loading timezones and modules synchronously.

Hardware: Fujitsu Futro S740 (HAOS)

Extracted logs:
Detected blocking call to open with args ('/usr/share/zoneinfo/UTC', 'rb') inside the event loop by custom integration 'ics_calendar' at custom_components/ics_calendar/parsers/parser_rie.py, line 6: import recurring_ical_events as rie

Detected blocking call to import_module with args ('tzdata',) inside the event loop by custom integration 'ics_calendar' at custom_components/ics_calendar/parsers/parser_rie.py, line 6: import recurring_ical_events as rie

Detected blocking call to walk with args ('/usr/share/zoneinfo',) inside the event loop by custom integration 'ics_calendar' at custom_components/ics_calendar/parsers/parser_rie.py, line 6: import recurring_ical_events as rie
