### ISSUE TITLE
ICS Calendar integration broke after update to 2025.0b2

### ISSUE THREAD

**Issue by smartmatic** [franc6/ics_calendar#214]
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version:

Installation Type (put an X between the square brackets for your HA):
[x] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[x] ARM
[] x86-64

**Describe the bug**
Integration does no longer start after update to current beta

Error message:
’’’
Logger: homeassistant.config_entries
Quelle: config_entries.py:640
Erstmals aufgetreten: 08:47:34 (2 Vorkommnisse)
Zuletzt protokolliert: 09:01:37

Error setting up entry for ics_calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ics_calendar/calendar.py", line 49, in <module>
    from .getparser import GetParser
  File "/config/custom_components/ics_calendar/getparser.py", line 5, in <module>
    from .parsers.parser_rie import ParserRIE
  File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 6, in <module>
    import recurring_ical_events as rie
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1530, in <module>
    class CalendarQuery:
    ...<193 lines>...
            raise IndexError("No components found.")
  File "/usr/local/lib/python3.13/site-packages/recurring_ical_events.py", line 1547, in CalendarQuery
    icalendar.InvalidCalendar,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'icalendar' has no attribute 'InvalidCalendar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/__init__.py", line 206, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, ["calendar"])
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1185, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1098, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1292, in _load_platform
    raise ImportError(
        f"Exception importing {self.pkg_path}.{platform_name}"
    ) from err
ImportError: Exception importing custom_components.ics_calendar.calendar
’’’

**Comment by franc6** [comment]
Thanks for the report. I hope to work on this before year’s end, but no promises.

**Comment by pdsccode** [comment]
@smartmatic: I had the same issue. Disabling the integration, restarting HA, enabling the integration and once again restarting solved it for me. Maybe it was just a temporary issue? 🤔

**Comment by franc6** [comment]
After further testing, I think this is just another instance of #190.

**Comment by franc6** [comment]
After much pain and consideration, I've determined that I can't really work around this problem.  Please see the new notes in README.md.  I know that's not what anyone posting to this issue wants to read, but I'm stuck.  There's nothing I can do to make it work.  If you can reproduce the problem on a clean installation without any attempt to resolve this problem, please re-open https://github.com/home-assistant/core/issues/127966 with HA, or, if more appropriate, open a new issue with HA and note that the one I referenced is not fixed.
If you cannot reproduce the problem on a clean installation, then you probably need to clean up whatever changes you've made to fix or work-around this problem, uninstall this integration, and re-install it.
I'm really sorry, this isn't the way I wanted to close this issue, either.  :(
