### ISSUE TITLE
0.98.1 Error importing arrow

### ISSUE THREAD

**Issue by vbtrek** [franc6/ics_calendar#4]
Just installed on the latest home assistant 0.98.1 and get the following error:

```
2019-09-01 21:27:52 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.ics. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 355, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/ics/__init__.py", line 2, in <module>
    from .calendar import VERSION
  File "/config/custom_components/ics/calendar.py", line 8, in <module>
    import arrow
ModuleNotFoundError: No module named 'arrow'

```

**Comment by franc6** [comment]
Did you install through HACS or do a manual installation?  I suspect the manual install instructions have some holes -- they're mostly copied from a template. :(

**Comment by vbtrek** [comment]
It was a manual install as I didn't have HACS. Works fine now I have re-installed with HACS. Thanks

**Comment by franc6** [comment]
Instructions are incomplete.
