### ISSUE TITLE
Your custom component isn't working when using release version.

### ISSUE THREAD

**Issue by gieljnssns** [franc6/ics_calendar#41]
I'm trying your `release_version` because I wanted to solve https://github.com/franc6/ics_calendar/issues/40

Config ics parser
```
calendar:
  - platform: ics_calendar
    calendars:
      - name: "RAFC2"
        parser: ics
        url: "https://www.voetbalkrant.com/soccer/calendar/team/team_2_nl.ics"

  - platform: ics_calendar
    calendars:
      - name: "RAFC"
        parser: ics
        url: "https://ics.maak-agenda.nl/v2/rafc-antwerp.ics?85029616d9c3ec7e"

  - platform: ics_calendar
    calendars:
      - name: "Belgie Verlof"
        parser: ics
        includeAllDay: True
        url: "https://www.google.com/calendar/ical/feestdagenbelgie%40gmail.com/public/basic.ics"
```

I have enabled debugging
```
logger:
  default: error
  logs:
    homeassistant.components.script: debug
    homeassistant.components.shelly: critical
    custom_components.ics_calendar: debug
    ics: debug
    icalevents: debug
```
This gives me as error 
```
2021-12-13 15:00:09 DEBUG (SyncWorker_2) [custom_components.ics_calendar.calendar] Setting up ics calendars
2021-12-13 15:00:09 DEBUG (SyncWorker_2) [custom_components.ics_calendar.calendar] Initializing calendar: RAFC2
2021-12-13 15:00:09 DEBUG (SyncWorker_1) [custom_components.ics_calendar.calendar] Setting up ics calendars
2021-12-13 15:00:09 DEBUG (SyncWorker_1) [custom_components.ics_calendar.calendar] Initializing calendar: RAFC
2021-12-13 15:00:09 DEBUG (SyncWorker_4) [custom_components.ics_calendar.calendar] Setting up ics calendars
2021-12-13 15:00:09 DEBUG (SyncWorker_4) [custom_components.ics_calendar.calendar] Initializing calendar: Belgie Verlof
2021-12-13 15:01:10 ERROR (SyncWorker_4) [custom_components.ics_calendar.calendar] RAFC2: Failed to parse ICS!
2021-12-13 15:01:11 ERROR (SyncWorker_0) [custom_components.ics_calendar.calendar] RAFC: Failed to parse ICS!
2021-12-13 15:01:13 ERROR (SyncWorker_3) [custom_components.ics_calendar.calendar] Belgie Verlof: Failed to parse ICS!
```

Now I tried to use 
```
calendar:
  - platform: ics_calendar
    calendars:
      - name: "RAFC2"
        # parser: ics
        url: "https://www.voetbalkrant.com/soccer/calendar/team/team_2_nl.ics"

  - platform: ics_calendar
    calendars:
      - name: "RAFC"
        # parser: ics
        url: "https://ics.maak-agenda.nl/v2/rafc-antwerp.ics?85029616d9c3ec7e"

  - platform: ics_calendar
    calendars:
      - name: "Belgie Verlof"
        # parser: ics
        includeAllDay: True
        url: "https://www.google.com/calendar/ical/feestdagenbelgie%40gmail.com/public/basic.ics"
```
so I should parse as ical and it gives me this errors
```
2021-12-13 14:50:13 DEBUG (SyncWorker_2) [custom_components.ics_calendar.calendar] Setting up ics calendars
2021-12-13 14:50:13 DEBUG (SyncWorker_2) [custom_components.ics_calendar.calendar] Initializing calendar: RAFC2
2021-12-13 14:50:13 DEBUG (SyncWorker_0) [custom_components.ics_calendar.calendar] Setting up ics calendars
2021-12-13 14:50:13 DEBUG (SyncWorker_0) [custom_components.ics_calendar.calendar] Initializing calendar: RAFC
2021-12-13 14:50:13 DEBUG (SyncWorker_4) [custom_components.ics_calendar.calendar] Setting up ics calendars
2021-12-13 14:50:13 DEBUG (SyncWorker_4) [custom_components.ics_calendar.calendar] Initializing calendar: Belgie Verlof
2021-12-13 14:50:45 ERROR (MainThread) [custom_components.ics_calendar.calendar] RAFC2: Failed to parse ICS!
2021-12-13 14:50:45 ERROR (MainThread) [custom_components.ics_calendar.calendar] RAFC: Failed to parse ICS!
2021-12-13 14:50:45 ERROR (MainThread) [custom_components.ics_calendar.calendar] Belgie Verlof: Failed to parse ICS!
2021-12-13 14:51:13 ERROR (SyncWorker_1) [custom_components.ics_calendar.calendar] RAFC2: Failed to parse ICS!
2021-12-13 14:51:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc2 fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:51:13 ERROR (SyncWorker_4) [custom_components.ics_calendar.calendar] Belgie Verlof: Failed to parse ICS!
2021-12-13 14:51:13 ERROR (SyncWorker_3) [custom_components.ics_calendar.calendar] RAFC: Failed to parse ICS!
2021-12-13 14:51:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:52:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc2 fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:52:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:53:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc2 fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:53:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:54:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc2 fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:54:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:55:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc2 fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:55:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:56:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc2 fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
2021-12-13 14:56:13 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.rafc fails
Traceback (most recent call last):
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/Users/giel/Github/core/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/giel/Github/core/config/custom_components/ics_calendar/calendar.py", line 139, in update
    self._attr_extra_state_attributes = { "offset_reached": is_offset_reached(event) }
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 129, in is_offset_reached
    start = get_date(event["start"])
  File "/Users/giel/Github/core/homeassistant/components/calendar/__init__.py", line 66, in get_date
    if "date" in date:
TypeError: argument of type 'datetime.datetime' is not iterable
```

**Comment by franc6** [comment]
I'm sorry for the late reply, if you can upload a sample ICS file (with event tiles and descriptions changed to remove anything personal), I can take a look at this sometime in January.  Thanks!

**Comment by gieljnssns** [comment]
Those files are public available on those urls.

**Comment by franc6** [comment]
I found the problem; I left a typo in the current code, which caused the failure and subsequent exception reported in your logs; this will happen on every calendar, and wasn't specific to yours.

**Comment by franc6** [comment]
Not quite fixed yet...
