### ISSUE TITLE
tatsu.exceptions.FailedToken: (1:22) expecting '\r\n'

### ISSUE THREAD

**Issue by micksel** [franc6/ics_calendar#5]
I have installed the component on Hass.io with HACL but I receive and error when I try to use it.

2020-01-14 18:35:20 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.lillemor2 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 76, in parse
    ast = GRAMMAR.parse(line + CRLF)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 1042, in parse
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 226, in parse
    raise self._furthest_exception
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 218, in parse
    result = rule()
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 782, in parse
    result = self._parse_rhs(ctx, self.exp)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 790, in _parse_rhs
    result = ctx._call(ruleinfo)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 519, in _call
    result = self._recursive_call(ruleinfo)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 548, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 595, in _invoke_rule
    ruleinfo.impl(self)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 390, in parse
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 390, in <listcomp>
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 733, in parse
    return rule()
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 782, in parse
    result = self._parse_rhs(ctx, self.exp)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 790, in _parse_rhs
    result = ctx._call(ruleinfo)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 519, in _call
    result = self._recursive_call(ruleinfo)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 548, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 595, in _invoke_rule
    ruleinfo.impl(self)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 390, in parse
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 390, in <listcomp>
    ctx.last_node = [s.parse(ctx) for s in self.sequence]
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 733, in parse
    return rule()
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 782, in parse
    result = self._parse_rhs(ctx, self.exp)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 790, in _parse_rhs
    result = ctx._call(ruleinfo)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 519, in _call
    result = self._recursive_call(ruleinfo)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 548, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 595, in _invoke_rule
    ruleinfo.impl(self)
  File "/usr/local/lib/python3.7/site-packages/tatsu/grammars.py", line 296, in parse
    return ctx._token(self.token)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 632, in _token
    self._error(token, exclass=FailedToken)
  File "/usr/local/lib/python3.7/site-packages/tatsu/contexts.py", line 453, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedToken: (1:22) expecting '\r\n' :
TZID:Europe/Stockholm                
                     ^
CRLF
contentline
start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ics/calendar.py", line 97, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/ics/calendar.py", line 159, in update
    calendar = Calendar(urlopen(self.url).read().decode())
  File "/usr/local/lib/python3.7/site-packages/ics/icalendar.py", line 63, in __init__
    containers = calendar_string_to_containers(imports)
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 200, in calendar_string_to_containers
    return string_to_container(string)
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 183, in string_to_container
    return lines_to_container(txt.splitlines())
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 179, in lines_to_container
    return parse(tokenize_line(unfold_lines(lines)))
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 172, in parse
    res.append(Container.parse(line.value, tokenized_lines))
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 126, in parse
    items.append(Container.parse(line.value, tokenized_lines))
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 124, in parse
    for line in tokenized_lines:
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 165, in tokenize_line
    yield ContentLine.parse(line)
  File "/usr/local/lib/python3.7/site-packages/ics/grammar/parse.py", line 78, in parse
    raise ParseError()
ics.grammar.parse.ParseError

**Comment by franc6** [comment]
The error indicates there's something wrong with the calendar it downloaded.  We can try a few things to trouble-shoot this, in case there's nothing wrong with the calendar.

1) Can you download the calendar file separately, using, e.g. curl or wget?  If so, are you willing to post it here, or send it to me privately?  If so, I can take a look at it, see if I think it looks wrong, and if not, create a small example to reproduce the problem with the library I use to parse the calendar.  If that shows a problem, I can submit it as a bug to the author of the library.  Otherwise, I need to figure out what I did wrong in using the library. :)

2) If the file looks OK, I can give you a test build that will save the file before it parses it, and then compare the file it saved with the one you downloaded separately.  If they're different, then I get to trace why.  I'll likely need help with that, too.

3) If you don't want to share the file, do you know enough about the format to help track the problem?  If so, and if the calendar seems to contain no errors, then perhaps you can scrub any sensitive data before sending it to me, so I can investigate further.

Let me know how you want to proceed, please.

**Comment by micksel** [comment]
i censored the file so it could be ok to [share]( @url) 
[calendar (2).zip](https://github.com/franc6/ics_calendar/files/4061016/calendar.2.zip)

**Comment by franc6** [comment]
Thanks!  I see the problem, and can reproduce it with a simple example, too.  I'm going to see if I can add a work-around, and submit a bug report to the author of the component I'm using to parse it, since the author notes it can handle some calendars that don't comply with RFC 5545.  If you can tell me what produced it, that might help encourage the author to work-around the problem in his code, too (which is probably better than any quick work-around I can add).
For reference, the problem is that all (only most?) entries that indicate your time zone include several NULL characters at the end of the time zone specification.  NULL characters are not allowed, per RFC 5545.

**Comment by franc6** [comment]
See https://github.com/C4ptainCrunch/ics.py/issues/219 for the issue I added to the author of the ics library I'm using to parse the calendars.

**Comment by franc6** [comment]
Version 1.0.1 should work-around the problem, but I suspect this version will be a bit slower, as it's more of a sledge-hammer approach than a real fix. :)
