### ISSUE TITLE
Calendar parse fails on Home Assistant 2023.4.0b4

### ISSUE THREAD

**Issue by kulmegil** [franc6/ics_calendar#90]
One of my 2 calendars is no longer displaying on Home Assistant beta (spotted 2023.4.0b4 and newer... probably since first beta)

The same calendar works fine on latest stable 2023.3.6 using any parser type ("rie" or "ics").

The calendar fails even when it's served from local http server instead of usual url.

attached calendar: [ical.php](https://github.com/franc6/ics_calendar/files/11139756/ical.php.zip)

Error:
```
2023-04-03 15:43:58.599 ERROR (SyncWorker_2) [custom_components.ics_calendar.calendar] update: Kiedy Wywóz: Failed to parse ICS!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2023-04-04 00:00:00+02:00, 2023-04-04 00:00:00+02:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2023-04-04 00:00:00+02:00, 2023-04-04 00:00:00+02:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ics_calendar/calendar.py", line 291, in update
    self.event = self.parser.get_current_event(
  File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 139, in get_current_event
    return CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2023-04-04 00:00:00+02:00, 2023-04-04 00:00:00+02:00)
```

**Comment by kulmegil** [comment]
my bad

Just check and it appears that only "rie" parser crashes on beta and only with selected calendar

**Comment by franc6** [comment]
Thanks for the update!

**Comment by gitmesomepizza** [comment]
Just updated to 2023.4.0 today, and I am getting the same errors in my logs.

**Comment by gitmesomepizza** [comment]
Here are my logs. Parsers are failing for calendars with weekly/semi-weekly recurring events.
A sample ICS that has these failures can be downloaded at: [http://cal.my-waste.mobi/admin/calendars/527-FRE-collection-230-S1831.ics](url)
```
async_get_events: Recycling: Failed to parse ICS!

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2023-04-06 06:00:00-04:00, 2023-04-06 06:00:00-04:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2023-04-06 06:00:00-04:00, 2023-04-06 06:00:00-04:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/ics_calendar/calendar.py", line 267, in async_get_events
    event_list = self.parser.get_event_list(
  File "/config/custom_components/ics_calendar/parsers/parser_ics.py", line 78, in get_event_list
    calendar_event = CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2023-04-06 06:00:00-04:00, 202
```

**Comment by no0ner** [comment]
I'm having the exact same issue as @gitmesomepizza but using a Google Calendar ICS.
Tried ics and rie parser, none of them worked.
Also it's a calendar with recurring events.

**Comment by olexs** [comment]
Same here, my city publishes a calendar for trash pickup days that I use via ics_calendar. The events all are "instantaneous" at midnight with zero duration, which now seems to cause a validation error in the parser. It used to work perfectly before.

I believe the code causing the error has been added to HA itself, in the `calendar` component. A possible workaround would be to patch such events to have a 1-second duration or similar. A better solution would be to allow zero-length events in HA itself, this is outside the scope of this integration though.

**Comment by olexs** [comment]
HomeAssistant 2023.4.3 fixes this issue for me, the fix was implemented in https://github.com/home-assistant/core/pull/91129. No changes to the integration necessary.

**Comment by franc6** [comment]
Unfortunately, looking at the fix, this only addresses one of the problems. I might open another issue for HA, but for now, please be aware that some events will work with the update, but not everything. HA still has some very broken event validation rules.
