### ISSUE TITLE
Filtering not working @ 2023.5.2

### ISSUE THREAD

**Issue by mueller93** [franc6/ics_calendar#91]
I am getting an empty calendar when filtering for anything. I already tried regex and plain string, with multiple filters or even just one I see the following error in my logs and an empty calendar:

```
Error while setting up ics_calendar platform for calendar

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ics_calendar/calendar.py", line 127, in setup_platform
    calendar_devices.append(ICSCalendarEntity(entity_id, device_data))
  File "/config/custom_components/ics_calendar/calendar.py", line 148, in __init__
    self.data = ICSCalendarData(device_data)
  File "/config/custom_components/ics_calendar/calendar.py", line 230, in __init__
    Filter(device_data[CONF_EXCLUDE], device_data[CONF_INCLUDE])
  File "/config/custom_components/ics_calendar/filter.py", line 24, in __init__
    self._exclude = Filter.set_rules(exclude)
  File "/config/custom_components/ics_calendar/filter.py", line 39, in set_rules
    if rule.startswith("/"):
AttributeError: 'list' object has no attribute 'startswith'

``` 

My config looks something like this:

```
calendar:
- platform: ics_calendar
  calendars:
      - name: "IUBH Termine"
        url: "https://mycampus.iubh.de/calendar/export_execute.php?userid=4xxxx&authtoken=xyzprovidedauthtoken&preset_what=all&preset_time=recentupcoming"
        exclude: "['Sprechstunde'], ['Coaching'], ['Motivation']"
        include: "['/^dlb'/i]"
        days: 30
        include_all_day: True
        download_interval: 15

``` 

I didn't try the calendar in any version before as I just included it. 
I'm currently on the latest version (2023.5.2 for HA and 2023.04.1 for the supervisor).

Maybe someone already has a solution for this?

**Comment by mueller93** [comment]
Okay this was my fault.
I just saw my issue with exclude and fixed it. 
Sorry for that.

**Comment by JOHLC** [comment]
> Okay this was my fault. I just saw my issue with exclude and fixed it. Sorry for that.

How did you fix this?
